local ForbiddenEvents = {
	"8321hiue89js",
	"adminmenu:allowall",
	"AdminMenu:giveBank",
	"AdminMenu:giveCash",
	"AdminMenu:giveDirtyMoney",
	"Tem2LPs5Para5dCyjuHm87y2catFkMpV",
	"dqd36JWLRC72k8FDttZ5adUKwvwq9n9m",
	"antilynx8:anticheat",
	"antilynxr4:detect",
	"antilynxr6:detection",
	"ynx8:anticheat",
	"antilynx8r4a:anticheat",
	"lynx8:anticheat",
	"AntiLynxR4:kick",
	"AntiLynxR4:log",
	"bank:deposit",
	"bank:withdraw",
	"Banca:deposit",
	"Banca:withdraw",
	"BsCuff:Cuff696999",
	"CheckHandcuff",
	"cuffServer",
	"cuffGranted",
	"DiscordBot:playerDied",
	"DFWM:adminmenuenable",
	"DFWM:askAwake",
	"DFWM:checkup",
	"DFWM:cleanareaentity",
	"DFWM:cleanareapeds",
	"DFWM:cleanareaveh",
	"DFWM:enable",
	"DFWM:invalid",
	"DFWM:log",
	"DFWM:openmenu",
	"DFWM:spectate",
	"DFWM:ViolationDetected",
	"dmv:success",
	"eden_garage:payhealth",
	"ems:revive",
	"hentailover:xdlol",
	"JailUpdate",
	"js:jailuser",
	"js:removejailtime",
	"LegacyFuel:PayFuel",
	"ljail:jailplayer",
	"lscustoms:payGarage",
	"mellotrainer:adminTempBan",
	"mellotrainer:adminKick",
	"mellotrainer:s_adminKill",
	"NB:destituerplayer",
	"NB:recruterplayer",
	"OG_cuffs:cuffCheckNearest",
	"paramedic:revive",
	"police:cuffGranted",
	"unCuffServer",
	"uncuffGranted",
	"vrp_slotmachine:server:2",
	"whoapd:revive",
	"gcPhone:_internalAddMessageDFWM",
	"gcPhone:tchat_channelDFWM",
	"esx_vehicleshop:setVehicleOwnedDFWM",
	"esx_mafiajob:confiscateDFWMPlayerItem",
	"_chat:messageEntDFWMered",
	"lscustoms:pDFWMayGarage",
	"vrp_slotmachDFWMine:server:2",
	"Banca:dDFWMeposit",
	"bank:depDFWMosit",
	"esx_jobs:caDFWMution",
	"give_back",
	"esx_fueldDFWMelivery:pay",
	"esx_carthDFWMief:pay",
	"esx_godiDFWMrtyjob:pay",
	"esx_pizza:pDFWMay",
	"esx_ranger:pDFWMay",
	"esx_garbageDFWMjob:pay",
	"esx_truckDFWMerjob:pay",
	"AdminMeDFWMnu:giveBank",
	"AdminMDFWMenu:giveCash",
	"esx_goDFWMpostaljob:pay",
	"esx_baDFWMnksecurity:pay",
	"esx_sloDFWMtmachine:sv:2",
	"esx:giDFWMveInventoryItem",
	"NB:recDFWMruterplayer",
	"esx_biDFWMlling:sendBill",
	"esx_jDFWMailer:sendToJail",
	"esx_jaDFWMil:sendToJail",
	"js:jaDFWMiluser",
	"esx-qalle-jail:jailPDFWMlayer",
	"esx_dmvschool:pDFWMay",
	"LegacyFuel:PayFuDFWMel",
	"OG_cuffs:cuffCheckNeDFWMarest",
	"CheckHandcDFWMuff",
	"cuffSeDFWMrver",
	"cuffGDFWMranted",
	"police:cuffGDFWMranted",
	"esx_handcuffs:cufDFWMfing",
	"esx_policejob:haDFWMndcuff",
	"bank:withdDFWMraw",
	"dmv:succeDFWMss",
	"esx_skin:responseSaDFWMveSkin",
	"esx_dmvschool:addLiceDFWMnse",
	"esx_mechanicjob:starDFWMtCraft",
	"esx_drugs:startHarvestWDFWMeed",
	"esx_drugs:startTransfoDFWMrmWeed",
	"esx_drugs:startSellWeDFWMed",
	"esx_drugs:startHarvestDFWMCoke",
	"esx_drugs:startTransDFWMformCoke",
	"esx_drugs:startSellCDFWMoke",
	"esx_drugs:startHarDFWMvestMeth",
	"esx_drugs:startTDFWMransformMeth",
	"esx_drugs:startSellMDFWMeth",
	"esx_drugs:startHDFWMarvestOpium",
	"esx_drugs:startSellDFWMOpium",
	"esx_drugs:starDFWMtTransformOpium",
	"esx_blanchisDFWMseur:startWhitening",
	"esx_drugs:stopHarvDFWMestCoke",
	"esx_drugs:stopTranDFWMsformCoke",
	"esx_drugs:stopSellDFWMCoke",
	"esx_drugs:stopHarvesDFWMtMeth",
	"esx_drugs:stopTranDFWMsformMeth",
	"esx_drugs:stopSellMDFWMeth",
	"esx_drugs:stopHarDFWMvestWeed",
	"esx_drugs:stopTDFWMransformWeed",
	"esx_drugs:stopSellWDFWMeed",
	"esx_drugs:stopHarvestDFWMOpium",
	"esx_drugs:stopTransDFWMformOpium",
	"esx_drugs:stopSellOpiuDFWMm",
	"esx_society:openBosDFWMsMenu",
	"esx_jobs:caDFWMution",
	"esx_tankerjob:DFWMpay",
	"esx_vehicletrunk:givDFWMeDirty",
	"gambling:speDFWMnd",
	"AdminMenu:giveDirtyMDFWMoney",
	"esx_moneywash:depoDFWMsit",
	"esx_moneywash:witDFWMhdraw",
	"mission:completDFWMed",
	"truckerJob:succeDFWMss",
	"99kr-burglary:addMDFWMoney",
	"esx_jailer:unjailTiDFWMme",
	"esx_ambulancejob:reDFWMvive",
	"DiscordBot:plaDFWMyerDied",
	"esx:getShDFWMaredObjDFWMect",
	"esx_society:getOnlDFWMinePlayers",
	"js:jaDFWMiluser",
	"h:xd",
	"adminmenu:setsalary",
	"adminmenu:cashoutall",
	"bank:tranDFWMsfer",
	"paycheck:bonDFWMus",
	"paycheck:salDFWMary",
	"HCheat:TempDisableDetDFWMection",
	"esx_drugs:pickedUpCDFWMannabis",
	"esx_drugs:processCDFWMannabis",
	"esx-qalle-hunting:DFWMreward",
	"esx-qalle-hunting:seDFWMll",
	"esx_mecanojob:onNPCJobCDFWMompleted",
	"BsCuff:Cuff696DFWM999",
	"veh_SR:CheckMonDFWMeyForVeh",
	"esx_carthief:alertcoDFWMps",
	"mellotrainer:adminTeDFWMmpBan",
	"mellotrainer:adminKickDFWM",
	"esx_society:putVehicleDFWMInGarage"
}

CreateThread(function()
	for i, eventName in ipairs(ForbiddenEvents) do
			RegisterNetEvent(eventName)
			AddEventHandler(eventName, function()
					BanPlayer(source, "Event Hacker", 69)
			end)
	end
end)

local BlacklistModels = { 
	[`HYDRA`] = true,
	[`stt_prop_stunt_track_dwslope30`] = true,
	[`sr_prop_spec_tube_crn_05a`] = true,
[`sr_prop_spec_tube_crn_30d_05a`] = true,
[`sr_prop_spec_tube_l_05a`] = true,
[`sr_prop_spec_tube_m_05a`] = true,
[`sr_prop_spec_tube_xxs_05a`] = true,
[`sr_prop_stunt_tube_crn_15d_05a`] = true,
[`sr_prop_stunt_tube_crn_5d_05a`] = true,
[`sr_prop_stunt_tube_xs_05a`] = true,
[`sr_prop_special_bblock_lrg11`] = true,
[`sr_prop_special_bblock_lrg2`] = true,
[`sr_prop_special_bblock_lrg3`] = true,
[`sr_prop_special_bblock_mdm1`] = true,
[`sr_prop_special_bblock_mdm2`] = true,
[`sr_prop_special_bblock_mdm3`] = true,
[`sr_prop_special_bblock_sml1`] = true,
[`sr_prop_special_bblock_sml2`] = true,
[`sr_prop_special_bblock_sml3`] = true,
[`sr_prop_special_bblock_xl1`] = true,
[`sr_prop_special_bblock_xl2`] = true,
[`sr_prop_special_bblock_xl3`] = true,
[`sr_prop_special_bblock_xl3_fixed`] = true,
[`sr_prop_sr_target_1_01a`] = true,
[`sr_prop_sr_target_2_04a`] = true,
[`sr_prop_sr_target_3_03a`] = true,
[`sr_prop_sr_target_5_01a`] = true,
[`sr_prop_sr_target_large_01a`] = true,
[`sr_prop_sr_target_long_01a`] = true,
[`sr_prop_sr_target_small_01a`] = true,
[`sr_prop_sr_target_small_02a`] = true,
[`sr_prop_sr_target_small_03a`] = true,
[`sr_prop_sr_target_small_04a`] = true,
[`sr_prop_sr_target_small_05a`] = true,
[`sr_prop_sr_target_small_06a`] = true,
[`sr_prop_sr_target_small_07a`] = true,
[`sr_prop_sr_target_trap_01a`] = true,
[`sr_prop_sr_target_trap_02a`] = true,
[`sr_prop_sr_track_block_01`] = true,
[`sr_prop_sr_track_wall`] = true,
[`sr_prop_sr_tube_end`] = true,
[`sr_prop_sr_tube_wall`] = true,
[`sr_prop_spec_target_b_01a`] = true,
[`sr_prop_spec_target_m_01a`] = true,
[`sr_prop_spec_target_s_01a`] = true,
[`sr_prop_spec_tube_refill`] = true,
[`sr_prop_track_refill`] = true,
[`sr_prop_track_refill_t1`] = true,
[`sr_prop_track_refill_t2`] = true,
[`sr_mp_spec_races_ammu_sign`] = true,
[`sr_mp_spec_races_blimp_sign`] = true,
[`sr_mp_spec_races_ron_sign`] = true,
[`sr_mp_spec_races_xero_sign`] = true,
[`sr_prop_sr_start_line_02`] = true,
[`sr_prop_track_straight_l_d15`] = true,
[`sr_prop_track_straight_l_d30`] = true,
[`sr_prop_track_straight_l_d45`] = true,
[`sr_prop_track_straight_l_d5`] = true,
[`sr_prop_track_straight_l_u15`] = true,
[`sr_prop_track_straight_l_u30`] = true,
[`sr_prop_track_straight_l_u45`] = true,
[`sr_prop_track_straight_l_u5`] = true,
[`sr_prop_spec_tube_crn_01a`] = true,
[`sr_prop_spec_tube_crn_30d_01a`] = true,
[`sr_prop_spec_tube_l_01a`] = true,
[`sr_prop_spec_tube_m_01a`] = true,
[`sr_prop_spec_tube_s_01a`] = true,
[`sr_prop_spec_tube_xxs_01a`] = true,
[`sr_prop_stunt_tube_crn_15d_01a`] = true,
[`sr_prop_stunt_tube_crn_5d_01a`] = true,
[`sr_prop_stunt_tube_crn2_01a`] = true,
[`sr_prop_stunt_tube_xs_01a`] = true,
[`sr_prop_spec_tube_crn_03a`] = true,
[`sr_prop_spec_tube_crn_30d_03a`] = true,
[`sr_prop_spec_tube_l_03a`] = true,
[`sr_prop_spec_tube_m_03a`] = true,
[`sr_prop_spec_tube_s_03a`] = true,
[`sr_prop_spec_tube_xxs_03a`] = true,
[`sr_prop_stunt_tube_crn_15d_03a`] = true,
[`sr_prop_stunt_tube_crn_5d_03a`] = true,
[`sr_prop_stunt_tube_crn2_03a`] = true,
[`sr_prop_stunt_tube_xs_03a`] = true,
[`sr_prop_spec_tube_crn_02a`] = true,
[`sr_prop_spec_tube_crn_30d_02a`] = true,
[`sr_prop_spec_tube_l_02a`] = true,
[`sr_prop_spec_tube_m_02a`] = true,
[`sr_prop_spec_tube_s_02a`] = true,
[`sr_prop_spec_tube_xxs_02a`] = true,
[`sr_prop_stunt_tube_crn_15d_02a`] = true,
[`sr_prop_stunt_tube_crn_5d_02a`] = true,
[`sr_prop_stunt_tube_crn2_02a`] = true,
[`sr_prop_stunt_tube_xs_02a`] = true,
[`sr_prop_spec_tube_crn_04a`] = true,
[`sr_prop_spec_tube_crn_30d_04a`] = true,
[`sr_prop_spec_tube_l_04a`] = true,
[`sr_prop_spec_tube_m_04a`] = true,
[`sr_prop_spec_tube_s_04a`] = true,
[`sr_prop_spec_tube_xxs_04a`] = true,
[`sr_prop_stunt_tube_crn_15d_04a`] = true,
[`sr_prop_stunt_tube_crn_5d_04a`] = true,
[`sr_prop_stunt_tube_crn2_04a`] = true,
[`sr_prop_stunt_tube_xs_04a`] = true,
[`stt_prop_race_tannoy`] = true,
[`stt_prop_speakerstack_01a`] = true,
[`stt_prop_flagpole_1c`] = true,
[`stt_prop_flagpole_1e`] = true,
[`stt_prop_flagpole_1d`] = true,
[`stt_prop_flagpole_1f`] = true,
[`stt_prop_flagpole_1a`] = true,
[`stt_prop_flagpole_1b`] = true,
[`stt_prop_flagpole_2a`] = true,
[`stt_prop_flagpole_2b`] = true,
[`stt_prop_flagpole_2c`] = true,
[`stt_prop_flagpole_2d`] = true,
[`stt_prop_flagpole_2e`] = true,
[`stt_prop_flagpole_2f`] = true,
[`stt_prop_corner_sign_01`] = true,
[`stt_prop_corner_sign_02`] = true,
[`stt_prop_corner_sign_03`] = true,
[`stt_prop_corner_sign_04`] = true,
[`stt_prop_corner_sign_05`] = true,
[`stt_prop_corner_sign_06`] = true,
[`stt_prop_corner_sign_07`] = true,
[`stt_prop_corner_sign_08`] = true,
[`stt_prop_corner_sign_09`] = true,
[`stt_prop_corner_sign_10`] = true,
[`stt_prop_corner_sign_11`] = true,
[`stt_prop_corner_sign_12`] = true,
[`stt_prop_corner_sign_13`] = true,
[`stt_prop_corner_sign_14`] = true,
[`stt_prop_hoop_constraction_01a`] = true,
[`stt_prop_hoop_small_01`] = true,
[`stt_prop_hoop_tyre_01a`] = true,
[`stt_prop_race_gantry_01`] = true,
[`stt_prop_race_start_line_01`] = true,
[`stt_prop_race_start_line_01b`] = true,
[`stt_prop_race_start_line_02`] = true,
[`stt_prop_race_start_line_02b`] = true,
[`stt_prop_race_start_line_03`] = true,
[`stt_prop_race_start_line_03b`] = true,
[`stt_prop_ramp_adj_flip_m`] = true,
[`stt_prop_ramp_adj_flip_mb`] = true,
[`stt_prop_ramp_adj_flip_s`] = true,
[`stt_prop_ramp_adj_flip_sb`] = true,
[`stt_prop_ramp_adj_hloop`] = true,
[`stt_prop_ramp_adj_loop`] = true,
[`stt_prop_ramp_jump_l`] = true,
[`stt_prop_ramp_jump_m`] = true,
[`stt_prop_ramp_jump_s`] = true,
[`stt_prop_ramp_jump_xl`] = true,
[`stt_prop_ramp_jump_xs`] = true,
[`stt_prop_ramp_jump_xxl`] = true,
[`stt_prop_ramp_multi_loop_rb`] = true,
[`stt_prop_ramp_spiral_l`] = true,
[`stt_prop_ramp_spiral_l_l`] = true,
[`stt_prop_ramp_spiral_l_m`] = true,
[`stt_prop_ramp_spiral_l_s`] = true,
[`stt_prop_ramp_spiral_l_xxl`] = true,
[`stt_prop_ramp_spiral_m`] = true,
[`stt_prop_ramp_spiral_s`] = true,
[`stt_prop_ramp_spiral_xxl`] = true,
[`stt_prop_sign_circuit_01`] = true,
[`stt_prop_sign_circuit_02`] = true,
[`stt_prop_sign_circuit_03`] = true,
[`stt_prop_sign_circuit_04`] = true,
[`stt_prop_sign_circuit_05`] = true,
[`stt_prop_sign_circuit_06`] = true,
[`stt_prop_sign_circuit_07`] = true,
[`stt_prop_sign_circuit_08`] = true,
[`stt_prop_sign_circuit_09`] = true,
[`stt_prop_sign_circuit_10`] = true,
[`stt_prop_sign_circuit_11`] = true,
[`stt_prop_sign_circuit_11b`] = true,
[`stt_prop_sign_circuit_12`] = true,
[`stt_prop_sign_circuit_13`] = true,
[`stt_prop_sign_circuit_13b`] = true,
[`stt_prop_sign_circuit_14`] = true,
[`stt_prop_sign_circuit_14b`] = true,
[`stt_prop_sign_circuit_15`] = true,
[`stt_prop_slow_down`] = true,
[`stt_prop_startline_gantry`] = true,
[`stt_prop_stunt_bblock_huge_01`] = true,
[`stt_prop_stunt_bblock_huge_02`] = true,
[`stt_prop_stunt_bblock_huge_03`] = true,
[`stt_prop_stunt_bblock_huge_04`] = true,
[`stt_prop_stunt_bblock_huge_05`] = true,
[`stt_prop_stunt_bblock_hump_01`] = true,
[`stt_prop_stunt_bblock_hump_02`] = true,
[`stt_prop_stunt_bblock_lrg1`] = true,
[`stt_prop_stunt_bblock_lrg2`] = true,
[`stt_prop_stunt_bblock_lrg3`] = true,
[`stt_prop_stunt_bblock_mdm1`] = true,
[`stt_prop_stunt_bblock_mdm2`] = true,
[`stt_prop_stunt_bblock_mdm3`] = true,
[`stt_prop_stunt_bblock_qp`] = true,
[`stt_prop_stunt_bblock_qp2`] = true,
[`stt_prop_stunt_bblock_qp3`] = true,
[`stt_prop_stunt_bblock_sml1`] = true,
[`stt_prop_stunt_bblock_sml2`] = true,
[`stt_prop_stunt_bblock_sml3`] = true,
[`stt_prop_stunt_bblock_xl1`] = true,
[`stt_prop_stunt_bblock_xl2`] = true,
[`stt_prop_stunt_bblock_xl3`] = true,
[`stt_prop_stunt_bowling_ball`] = true,
[`stt_prop_stunt_bowling_pin`] = true,
[`stt_prop_stunt_bowlpin_stand`] = true,
[`stt_prop_stunt_domino`] = true,
[`stt_prop_stunt_jump15`] = true,
[`stt_prop_stunt_jump30`] = true,
[`stt_prop_stunt_jump45`] = true,
[`stt_prop_stunt_jump_l`] = true,
[`stt_prop_stunt_jump_lb`] = true,
[`stt_prop_stunt_jump_loop`] = true,
[`stt_prop_stunt_jump_m`] = true,
[`stt_prop_stunt_jump_mb`] = true,
[`stt_prop_stunt_jump_s`] = true,
[`stt_prop_stunt_jump_sb`] = true,
[`stt_prop_stunt_landing_zone_01`] = true,
[`stt_prop_stunt_ramp`] = true,
[`stt_prop_stunt_soccer_ball`] = true,
[`stt_prop_stunt_soccer_goal`] = true,
[`stt_prop_stunt_soccer_lball`] = true,
[`stt_prop_stunt_soccer_sball`] = true,
[`stt_prop_stunt_target`] = true,
[`stt_prop_stunt_target_small`] = true,
[`stt_prop_stunt_track_bumps`] = true,
[`stt_prop_stunt_track_cutout`] = true,
[`stt_prop_stunt_track_dwlink`] = true,
[`stt_prop_stunt_track_dwlink_02`] = true,
[`stt_prop_stunt_track_dwsh15`] = true,
[`stt_prop_stunt_track_dwshort`] = true,
[`stt_prop_stunt_track_dwslope15`] = true,
[`stt_prop_stunt_track_dwslope30`] = true,
[`stt_prop_stunt_track_dwslope45`] = true,
[`stt_prop_stunt_track_dwturn`] = true,
[`stt_prop_stunt_track_dwuturn`] = true,
[`stt_prop_stunt_track_exshort`] = true,
[`stt_prop_stunt_track_fork`] = true,
[`stt_prop_stunt_track_funlng`] = true,
[`stt_prop_stunt_track_funnel`] = true,
[`stt_prop_stunt_track_hill`] = true,
[`stt_prop_stunt_track_hill2`] = true,
[`stt_prop_stunt_track_jump`] = true,
[`stt_prop_stunt_track_link`] = true,
[`stt_prop_stunt_track_otake`] = true,
[`stt_prop_stunt_track_sh15`] = true,
[`stt_prop_stunt_track_sh30`] = true,
[`stt_prop_stunt_track_sh45`] = true,
[`stt_prop_stunt_track_sh45_a`] = true,
[`stt_prop_stunt_track_short`] = true,
[`stt_prop_stunt_track_slope15`] = true,
[`stt_prop_stunt_track_slope30`] = true,
[`stt_prop_stunt_track_slope45`] = true,
[`stt_prop_stunt_track_start`] = true,
[`stt_prop_stunt_track_start_02`] = true,
[`stt_prop_stunt_track_straight`] = true,
[`stt_prop_stunt_track_straightice`] = true,
[`stt_prop_stunt_track_st_01`] = true,
[`stt_prop_stunt_track_st_02`] = true,
[`stt_prop_stunt_track_turn`] = true,
[`stt_prop_stunt_track_turnice`] = true,
[`stt_prop_stunt_track_uturn`] = true,
[`stt_prop_stunt_tube_crn`] = true,
[`stt_prop_stunt_tube_crn2`] = true,
[`stt_prop_stunt_tube_crn_15d`] = true,
[`stt_prop_stunt_tube_crn_30d`] = true,
[`stt_prop_stunt_tube_crn_5d`] = true,
[`stt_prop_stunt_tube_cross`] = true,
[`stt_prop_stunt_tube_end`] = true,
[`stt_prop_stunt_tube_ent`] = true,
[`stt_prop_stunt_tube_fn_01`] = true,
[`stt_prop_stunt_tube_fn_02`] = true,
[`stt_prop_stunt_tube_fn_03`] = true,
[`stt_prop_stunt_tube_fn_04`] = true,
[`stt_prop_stunt_tube_fn_05`] = true,
[`stt_prop_stunt_tube_fork`] = true,
[`stt_prop_stunt_tube_gap_01`] = true,
[`stt_prop_stunt_tube_gap_02`] = true,
[`stt_prop_stunt_tube_gap_03`] = true,
[`stt_prop_stunt_tube_hg`] = true,
[`stt_prop_stunt_tube_jmp`] = true,
[`stt_prop_stunt_tube_jmp2`] = true,
[`stt_prop_stunt_tube_l`] = true,
[`stt_prop_stunt_tube_m`] = true,
[`stt_prop_stunt_tube_qg`] = true,
[`stt_prop_stunt_tube_s`] = true,
[`stt_prop_stunt_tube_speed`] = true,
[`stt_prop_stunt_tube_speeda`] = true,
[`stt_prop_stunt_tube_speedb`] = true,
[`stt_prop_stunt_tube_xs`] = true,
[`stt_prop_stunt_tube_xxs`] = true,
[`stt_prop_stunt_wideramp`] = true,
[`stt_prop_track_bend2_bar_l`] = true,
[`stt_prop_track_bend2_bar_l_b`] = true,
[`stt_prop_track_bend2_l`] = true,
[`stt_prop_track_bend2_l_b`] = true,
[`stt_prop_track_bend_15d`] = true,
[`stt_prop_track_bend_15d_bar`] = true,
[`stt_prop_track_bend_180d`] = true,
[`stt_prop_track_bend_180d_bar`] = true,
[`stt_prop_track_bend_30d`] = true,
[`stt_prop_track_bend_30d_bar`] = true,
[`stt_prop_track_bend_5d`] = true,
[`stt_prop_track_bend_5d_bar`] = true,
[`stt_prop_track_bend_bar_l`] = true,
[`stt_prop_track_bend_bar_l_b`] = true,
[`stt_prop_track_bend_bar_m`] = true,
[`stt_prop_track_bend_l`] = true,
[`stt_prop_track_bend_l_b`] = true,
[`stt_prop_track_bend_m`] = true,
[`stt_prop_track_block_01`] = true,
[`stt_prop_track_block_02`] = true,
[`stt_prop_track_block_03`] = true,
[`stt_prop_track_chicane_l`] = true,
[`stt_prop_track_chicane_l_02`] = true,
[`stt_prop_track_chicane_r`] = true,
[`stt_prop_track_chicane_r_02`] = true,
[`stt_prop_track_cross`] = true,
[`stt_prop_track_cross_bar`] = true,
[`stt_prop_track_fork`] = true,
[`stt_prop_track_fork_bar`] = true,
[`stt_prop_track_funnel`] = true,
[`stt_prop_track_funnel_ads_01a`] = true,
[`stt_prop_track_funnel_ads_01b`] = true,
[`stt_prop_track_funnel_ads_01c`] = true,
[`stt_prop_track_jump_01a`] = true,
[`stt_prop_track_jump_01b`] = true,
[`stt_prop_track_jump_01c`] = true,
[`stt_prop_track_jump_02a`] = true,
[`stt_prop_track_jump_02b`] = true,
[`stt_prop_track_jump_02c`] = true,
[`stt_prop_track_link`] = true,
[`stt_prop_track_slowdown`] = true,
[`stt_prop_track_slowdown_t1`] = true,
[`stt_prop_track_slowdown_t2`] = true,
[`stt_prop_track_speedup`] = true,
[`stt_prop_track_speedup_t1`] = true,
[`stt_prop_track_speedup_t2`] = true,
[`stt_prop_track_start`] = true,
[`stt_prop_track_start_02`] = true,
[`stt_prop_track_stop_sign`] = true,
[`stt_prop_track_straight_bar_l`] = true,
[`stt_prop_track_straight_bar_m`] = true,
[`stt_prop_track_straight_bar_s`] = true,
[`stt_prop_track_straight_l`] = true,
[`stt_prop_track_straight_lm`] = true,
[`stt_prop_track_straight_lm_bar`] = true,
[`stt_prop_track_straight_m`] = true,
[`stt_prop_track_straight_s`] = true,
[`stt_prop_track_tube_01`] = true,
[`stt_prop_track_tube_02`] = true,
[`stt_prop_tyre_wall_01`] = true,
[`stt_prop_tyre_wall_010`] = true,
[`stt_prop_tyre_wall_011`] = true,
[`stt_prop_tyre_wall_012`] = true,
[`stt_prop_tyre_wall_013`] = true,
[`stt_prop_tyre_wall_014`] = true,
[`stt_prop_tyre_wall_015`] = true,
[`stt_prop_tyre_wall_02`] = true,
[`stt_prop_tyre_wall_03`] = true,
[`stt_prop_tyre_wall_04`] = true,
[`stt_prop_tyre_wall_05`] = true,
[`stt_prop_tyre_wall_06`] = true,
[`stt_prop_tyre_wall_07`] = true,
[`stt_prop_tyre_wall_08`] = true,
[`stt_prop_tyre_wall_09`] = true,
[`stt_prop_tyre_wall_0l010`] = true,
[`stt_prop_tyre_wall_0l012`] = true,
[`stt_prop_tyre_wall_0l013`] = true,
[`stt_prop_tyre_wall_0l014`] = true,
[`stt_prop_tyre_wall_0l015`] = true,
[`stt_prop_tyre_wall_0l018`] = true,
[`stt_prop_tyre_wall_0l019`] = true,
[`stt_prop_tyre_wall_0l020`] = true,
[`stt_prop_tyre_wall_0l04`] = true,
[`stt_prop_tyre_wall_0l05`] = true,
[`stt_prop_tyre_wall_0l06`] = true,
[`stt_prop_tyre_wall_0l07`] = true,
[`stt_prop_tyre_wall_0l08`] = true,
[`stt_prop_tyre_wall_0l1`] = true,
[`stt_prop_tyre_wall_0l16`] = true,
[`stt_prop_tyre_wall_0l17`] = true,
[`stt_prop_tyre_wall_0l2`] = true,
[`stt_prop_tyre_wall_0l3`] = true,
[`stt_prop_tyre_wall_0r010`] = true,
[`stt_prop_tyre_wall_0r011`] = true,
[`stt_prop_tyre_wall_0r012`] = true,
[`stt_prop_tyre_wall_0r013`] = true,
[`stt_prop_tyre_wall_0r014`] = true,
[`stt_prop_tyre_wall_0r015`] = true,
[`stt_prop_tyre_wall_0r016`] = true,
[`stt_prop_tyre_wall_0r017`] = true,
[`stt_prop_tyre_wall_0r018`] = true,
[`stt_prop_tyre_wall_0r019`] = true,
[`stt_prop_tyre_wall_0r04`] = true,
[`stt_prop_tyre_wall_0r05`] = true,
[`stt_prop_tyre_wall_0r06`] = true,
[`stt_prop_tyre_wall_0r07`] = true,
[`stt_prop_tyre_wall_0r08`] = true,
[`stt_prop_tyre_wall_0r09`] = true,
[`stt_prop_tyre_wall_0r1`] = true,
[`stt_prop_tyre_wall_0r2`] = true,
[`stt_prop_tyre_wall_0r3`] = true,
[`stt_prop_wallride_01`] = true,
[`stt_prop_wallride_01b`] = true,
[`stt_prop_wallride_02`] = true,
[`stt_prop_wallride_02b`] = true,
[`stt_prop_wallride_04`] = true,
[`stt_prop_wallride_05`] = true,
[`stt_prop_wallride_05b`] = true,
[`stt_prop_wallride_45l`] = true,
[`stt_prop_wallride_45la`] = true,
[`stt_prop_wallride_45r`] = true,
[`stt_prop_wallride_45ra`] = true,
[`stt_prop_wallride_90l`] = true,
[`stt_prop_wallride_90lb`] = true,
[`stt_prop_wallride_90r`] = true,
[`stt_prop_wallride_90rb`] = true,
[1708919037] = true,
--[`prop_beach_fire`] = true,
[`prop_gas_pump_1a`] = true,
[`BLIMP`] = true
}

AddEventHandler('entityCreating', function(entity)
local entity = entity
if DoesEntityExist(entity) then
	local model = GetEntityModel(entity)
	local owner = NetworkGetEntityOwner(entity) or "Server"

	if BlacklistModels[model] then
		CancelEvent()
		if model ~= -150975354 then
			local coords = GetEntityCoords(entity)
			printOUT = "vector3("..tonumber(string.format("%.2f", coords["x"]))..", "..tonumber(string.format("%.2f", coords["y"]))..", "..tonumber(string.format("%.2f", coords["z"]))..")"
			local message = 'Prop with the name **'..model..'** [**'..entity..'**] was created, by **'..owner..'** (**'..GetPlayerName(owner)..'**).\nSpawned at: **'..printOUT..'**'
			sendToDiscord('Prop Created!', message, "1127128", GetConvar("discordWebhook", ""))
		end
	end
end
end)

function BanPlayer(playerId, reason, time)
	local src = playerId
	if src then
			local identifiers = GetPlayerIdentifiers(src)
			local name = GetPlayerName(src)

			local steamid  = "Unidentified"
			local license  = "Unidentified"
			local discord  = "Unidentified"
			local ip       = "Unidentified"
			local fivem    = "Unidentified"
	
			for k,v in pairs(GetPlayerIdentifiers(src))do            
					if string.sub(v, 1, string.len("steam:")) == "steam:" then
							steamid = v
					elseif string.sub(v, 1, string.len("license:")) == "license:" then
							license = v
					elseif string.sub(v, 1, string.len("ip:")) == "ip:" then
							ip = v
					elseif string.sub(v, 1, string.len("discord:")) == "discord:" then
							discord = v
					elseif string.sub(v, 1, string.len("fivem:")) == "fivem:" then
							fivem = v
					end
			end

			exports.oxmysql:insert("INSERT INTO bannedplayers (name, steamid, discord, license, ip, fivem, reason, executioner, date) VALUES (:name, :steamid, :discord, :license, :ip, :fivem, :reason, :executioner, :date)", { 
					name = name,
					steamid = steamid,
					discord = discord,
					license = license,
					ip = ip,
					fivem = fivem,
					reason = reason, 
					executioner = "Console",
					date = time
			}, function(banId)
					if banId then
							RefreshBans()
							local message = "```Name: "..name.."\nBan ID: "..banId.."\nSteam: "..steamid.."\nDiscord: "..discord.."\nFiveM: "..fivem.."\nLicense: "..license.."\nIP: "..ip.."\nPunishment Type: Ban ("..time..")\nReason: "..reason.."\nExecutioner: Console".."\n```"
							sendToDiscord('Player Banned', message, "16711680", webhook)
							if playerId ~= nil and playerId ~= "NULL" then
									if GetPlayerName(playerId) then
											DropPlayer(playerId, 'Banned: '..reason)
									end
							end
					end
			end)
	end
end

exports('BanPlayer', BanPlayer) -- exports['erp_adminmenu']:BanPlayer(src, 'Doing something weird with multichar.', 69)

RegisterNetEvent('erp_adminmenu:sendCommands')
AddEventHandler('erp_adminmenu:sendCommands', function(reason)
	BanPlayer(source, reason, 69)
end)

RegisterNetEvent('es_admin:all')
AddEventHandler('es_admin:all', function(type)
	BanPlayer(source, 'Triggered es_admin:all lol kid.', 69)
end)

RegisterNetEvent('es_admin:quick')
AddEventHandler('es_admin:quick', function(id, type)
	BanPlayer(source, 'Triggered es_admin:quick lol kid.', 69)
end)

RegisterNetEvent('es_admin:set')
AddEventHandler('es_admin:set', function(t, USER, GROUP)
	BanPlayer(source, 'Triggered es_admin:set lol kid.', 69)
end)